### PR TITLE
Do not add nil values to customfields object to fix user import errors

### LINKED ISSUE #147: Add MobileId and ProximityChipId to userload transform
This is what we currently do in Symphony:
```
 <!-- MOBILE ID and PROXIMITY CHIP ID  -->
        <!--****************-->
        <xsl:variable name="ACTIVEID">
            <xsl:if test="identifier[@type='mobileid'] or identifier[@type='proximity']">
                <xsl:for-each select="identifier[@type='mobileid']">
```

Except map them to custom fields `MobileId` and `ProximityChipId` respectively.

### PR DESCRIPTION
**Pull request by jgreben**
Even if `proximitychipid` is present, if `mobileid` is missing there will be a 422 unproccesable entity error in the userload.

Fixes https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/147

### CODE REVIEW

File: lib/xml_user.rb [hunk 1]
```diff
@@ -156,5 +162,6 @@ def add_user_to_hash
     @hash[:users] << @person_hash
 
     @hash[:totalRecords] = @hash[:users].size
+    pp @hash
```
Comment (shelleydoljack) [inline lib/xml_user.rb]: debugging cruft?

**Review by shelleydoljack — APPROVED** [review]
👍 feel free to merge once you remove the debugging cruft (if that's what it is).
