### PR TITLE
Use settings to store folio hostname for USERSBL config module

### LINKED ISSUE #232: overwrite FOLIO_HOST value in USERSBL okapi config
When we pull USERSBL okapi config, the value for FOLIO_HOST ends up being `https://folio-test.stanford.edu` so when we run the load_all_configurations task, we end up with the wrong URL. It should be whatever folio env we are loading to.

### PR DESCRIPTION
**Pull request by jgreben**
Fixes https://github.com/sul-dlss/folio-tasks/issues/232

### CODE REVIEW

File: tasks/helpers/configurations.rb [hunk 1]
```diff
@@ -41,10 +41,14 @@ def update_module_configs(config)
...
   def config_entry_json(file)
-    JSON.parse(File.read(file))
+    entry = JSON.parse(File.read(file))
+
+    entry['configs'][0]['module'] == 'USERSBL' && entry['configs'][0]['value'] = Settings.hostname
+    entry
   end
 
   def config_entry_post(hash)
+    puts hash.to_json
```
Comment (shelleydoljack) [inline tasks/helpers/configurations.rb]: cruft?

File: tasks/helpers/configurations.rb [hunk 2]
```diff
@@ -41,10 +41,14 @@ def update_module_configs(config)
   end
 
   def config_entry_json(file)
-    JSON.parse(File.read(file))
+    entry = JSON.parse(File.read(file))
+
+    entry['configs'][0]['module'] == 'USERSBL' && entry['configs'][0]['value'] = Settings.hostname
```
Comment (shelleydoljack) [inline tasks/helpers/configurations.rb:46]: Need the `https://`? At least that is what the value looks like when you pull from folio.

**Review by shelleydoljack — CHANGES_REQUESTED** [review]

File: tasks/helpers/configurations.rb (hunk 2 above)
Comment (jgreben) [reply tasks/helpers/configurations.rb:46]: I wouldn't think so. If you go to that hostname nginx redirects you to 443.

Comment (jgreben) [reply tasks/helpers/configurations.rb:46]: Well I just tried it and looks like it does need it. Updating PR and vault.

Comment (shelleydoljack) [reply tasks/helpers/configurations.rb:46]: This is why I'm confused:
Screen Shot 2023-07-28 at 4 06 01 PM
But now I even wonder if this configuration is needed since nobody should be resetting their password. 🤷

Comment (jgreben) [reply tasks/helpers/configurations.rb:46]: Either way I added it to the settings.

Comment (shelleydoljack) [reply tasks/helpers/configurations.rb:46]: Mylibrary is using the reset pin functionality.... which doesn't use password or mod-users-bl. But I guess we should still set this configuration?

Comment (jgreben) [reply tasks/helpers/configurations.rb:46]: Yes

**Review by shelleydoljack — APPROVED** [review]
